#include "importworker.h"

ImportWorker::ImportWorker(QString fileName, QObject *parent) :
    QObject(parent)
{
    //Take the filename and determine the filetype (in the beginning just .xyz)

    this->fileName = fileName;
    if(this->fileName.endsWith(".xyz"))
    {
        this->fileType = XYZ_ASCII;
    }
    else if(this->fileName.endsWith(".xyb"))
    {
        this->fileType = XYZ_BINARY;
    }

}

void ImportWorker::run()
{
    qDebug() << "Thread " << QThread::currentThread() << " is running";

    switch(this->fileType)
    {
    default:
    case XYZ_ASCII:
        import_XYZ_Ascii_File();
    break;
    case XYZ_BINARY:
        import_XYZ_Binary_File();
    break;
    }


}

void ImportWorker::import_XYZ_Ascii_File()
{
    //import the filename
    qDebug() << "opening file: " << this->fileName;

    QFile file(this->fileName);
    if(!file.open(QIODevice::ReadOnly | QIODevice::Text))
        return;

    qint64 totalSize = file.size();
    qint64 currentSize = 0;
    quint16 percent = 0;

    QTextStream inputStream(&file);
    QString line = inputStream.readLine();

    bool importerInfo = false;

    while(!line.isNull())
    {
        //BUG: First Line is not being imported...

        currentSize += line.size();

        qDebug() << "totalSize: " << totalSize;
        qDebug() << "currentSize" << currentSize;
        percent = (currentSize*100.0f)/totalSize;
        qDebug() << "percent" << percent;

        Point3D _newPoint;

        //Process the line
        QStringList lineparts = line.split(" ");

        if(lineparts.count() == 6)
        {
            //Probably Normal Faro Scene Export
            _newPoint.x = lineparts[0].toFloat();
            _newPoint.y = lineparts[1].toFloat();
            _newPoint.z = lineparts[2].toFloat();
            _newPoint.r = lineparts[3].toInt();
            _newPoint.g = lineparts[4].toInt();
            _newPoint.b = lineparts[5].toInt();
        }
        else if(lineparts.count() == 8 )
        {
            //Probably Faro Scene LT Export
            if(!importerInfo)
            {
                importerInfo = true;
                emit showInfoMessage("The imported file was probably generated by Faro Scene LT!");
            }
            _newPoint.x = lineparts[2].toFloat();
            _newPoint.y = lineparts[3].toFloat();
            _newPoint.z = lineparts[4].toFloat();
            _newPoint.r = lineparts[5].toInt();
            _newPoint.g = lineparts[6].toInt();
            _newPoint.b = lineparts[7].toInt();
        }


        //send the current point over to the panorama data container
        emit newPoint( _newPoint );

        qDebug() << _newPoint.toString();

        emit importStatus(percent);


        //read the next line
        line = inputStream.readLine();
    }

    file.close();

    //Everything else happens on the Thread (Importing, maybe calculating spherical coordinates, and sending over the data to the main data container

    //after importing send a finished signal
    emit importStatus(100);
}

void ImportWorker::import_XYZ_Binary_File()
{
    //TODO
}
